### ISSUE TITLE
Print UIImage

### ISSUE THREAD

**Issue by phuongtd57** [KevinGong2013/Printer#10]
Hi Kevin,

How to print image, pdf ???

**Comment by KevinGong2013** [comment]
work in progress.

**Comment by KevinGong2013** [comment]
I have added image cmd on master but my printer don't support  this cmd. can you help me debug these cmd? just clone and run example project.

**Comment by phuongtd57** [comment]
Ok, i will try it tomorrow, i am at home now :)

Vào Th 4, 17 thg 4, 2019 lúc 18:02 Kevin <notifications@github.com> đã viết:

**Comment by phuongtd57** [comment]
Hi Kevin,
Image cmd does not work, it prints nothing

**Comment by KevinGong2013** [comment]
😕

**Comment by KevinGong2013** [comment]
print nothing means printer will feed paper ?

**Comment by phuongtd57** [comment]
Bank payper

Vào Th 5, 18 thg 4, 2019 lúc 09:03 Kevin <notifications@github.com> đã viết:

**Comment by phuongtd57** [comment]
i send print result to you in email

**Comment by phuongtd57** [comment]
blank paper

**Comment by huynhphan89** [comment]
Did you guys solve this issue ?

**Comment by pylearndl** [comment]
> blank paper



> Did you guys solve this issue ?

Hi,

I have forked Kevin's git and update new ImageBlock which prints esc/pos image on thermal receipt printer. Check it our on my forked link

https://github.com/pylearndl/Printer
