### ISSUE TITLE
Type 'Block' has no member 'dividing'

### ISSUE THREAD

**Issue by RobertoPanzera** [KevinGong2013/Printer#11]
Hi I wanted to use your library but it doesn't work,
I took the code from the example and I get this error:
 var receipt = Receipt(
                .dividing,  **Type 'Block' has no member 'dividing'**
                .qr("Icey.Liao"),
                .dividing    )

**Comment by KevinGong2013** [comment]
`Printer` framework not build ?

**Comment by RobertoPanzera** [comment]
I added this line to the pod file:
pod 'Printer', '~> 2.0'

**Comment by KevinGong2013** [comment]
pod 'Printer',  :branch => 'master'

**Comment by RobertoPanzera** [comment]
with this: "pod 'Printer', :branch => 'master'"
i have this error: "[!] Unknown external source parameters for `Printer`: `{:branch=>"master"}`"

if I write this in pod file:
"pod 'Printer', :git => 'https://github.com/KevinGong2013/Printer.git', :branch => 'master'"
pod install work and have this message: "Installing Printer 2.0.5 (was 2.0.3)"

but I have error in xcode: "No such module 'Printer'" in Viewcontroller and "Use of unresolved identifier 'CentralManagerDelegate'; did you mean 'CBCentralManagerDelegate'?" in Printer folder

**Comment by KevinGong2013** [comment]
new version released.
