### ISSUE TITLE
Papar cut command

### ISSUE THREAD

**Issue by ravishkumar24** [KevinGong2013/Printer#2]
Hello Kevin, I have successfully implemented your code in my project and it really works like a charm, but I have searched in your code there is no command to cut paper partially or cut full and print any image. 
I have tried with the reference document attached with the example but i had no luck.
Can you please suggest me how to implement paper partially cut command and print image.

Thank you again for this wonderful project.

**Comment by KevinGong2013** [comment]
Sorry buddy, my printer does't support paper partially, so I can't give you some code.
you can check this: https://github.com/bamarni/escpos/blob/master/cut.go & https://github.com/petrkutalek/png2pos
