### ISSUE TITLE
Ticket is not included in the cocoapod

### ISSUE THREAD

**Issue by dragostouchbistro** [KevinGong2013/Printer#21]
Great job creating this project. I was able to include the files just fine. Thank you for working on it.

Only when I try to use it with Cocoapods, after running pod install, the `Ticket.swift` and many other sources are not downloaded. [See here](https://drive.google.com/file/d/1Is-NfGEe8YKZgqedtO6WZWP_W06mEY3g/view?usp=sharing)

**Comment by KevinGong2013** [comment]
sorry guys, may be you need update your repo.
``` shell 
pod repo update
pod update
```

**Comment by dragostouchbistro** [comment]
Yes, that fixed it. Thank you
