### ISSUE TITLE
Printing without extra Line

### ISSUE THREAD

**Issue by CedenoH07** [KevinGong2013/Printer#22]
It is possible to print without Extra space between lines? 

` var ticket = Ticket(
        .title("Recibo de Pago"),
        .dividing,
            .text(.init(content: "Test", predefined: .alignment(.center))),
            .text(.init(content: "", predefined: .alignment(.center))),
            .dividing,
            .text(.init(content: Date().description, predefined: .alignment(.center))),
            .kv(k: "Cliente:", v: nombreCliente),
            .kv(k: "# confirmacion:", v: numConfirmacion),
            .text(.init(content: "Detalle", predefined: .alignment(.center))),
            .kv(k: "Monto Pagado:", v: montoPagado),
            .kv(k: "Monto Restante", v: montoRestante),
            .dividing,
            Block(Text(content: "Gracias por su Pago", predefined: .alignment(.center)))
    )
        ticket.feedLinesOnHead = 0
        ticket.feedLinesOnTail = 0

        ReadyToPrint(ticket: ticket);
    }`

![TicketExample](https://user-images.githubusercontent.com/20801408/66726206-ea05b300-ee05-11e9-9ffa-19e1e24877af.jpeg)

**Comment by KevinGong2013** [comment]
#4
