### ISSUE TITLE
Unknown class _TtC7Printer26PrinterTableViewController in Interface Builder file.

### ISSUE THREAD

**Issue by rishi1596** [KevinGong2013/Printer#26]
When i run the sample code of latest release 4.0.1 and proceed to bluetooth list it gives the following error in logs "Unknown class _TtC7Printer26PrinterTableViewController in Interface Builder file" whereas if I run the sample code of release 3.0.7 it works fine and displays the list of devices available.

Tested on Xcode 11.1

Found the Issue - In the latest release 4.0.1 the custom class name of bluetooth list view controller in MainStoryBoard should be 'BluetoothPrinterSelectTableViewController' instead of 'PrinterTableViewController'

**Comment by KevinGong2013** [comment]
Xcode Menu => Product -> Clean Build Folder

Run Again.
