### ISSUE TITLE
Problems printing German letters

### ISSUE THREAD

**Issue by chnbz** [KevinGong2013/Printer#30]
Hi,

the printer doesn't print German letters like Ä,Ö or Ü instead it prints "ü0ë5" for example. Tried different code pages that the printer supports but not much has changed. Any idea how to resolve this?

**Comment by chnbz** [comment]
Solved it. Found out the print() function has an optional parameter called encoding 
![image](https://user-images.githubusercontent.com/228203/73650760-2db94c80-4683-11ea-86d3-f6fc69aa039c.png)

I changed the code page to WPC1252 as well on the printer and since then everything works fine.

**Comment by gardsgard** [comment]
How did you set the codePage? 
Having problems with åäö.

**Comment by chnbz** [comment]
> How did you set the codePage?
> Having problems with åäö.

With a Windows app that the printer manufacturer provided :)
