### ISSUE TITLE
Appstore rejection

### ISSUE THREAD

**Issue by apeksha-elluminati282** [KevinGong2013/Printer#40]
Hi KevinGong,

We have a project of food ordering & delivery APP which is live on AppStore right now.As per our client requirement users should be able to print receipt of order from app. So we have used this library to print receipt and it is working fine. But when we updating this functionality with new build on AppStore they are demanding MFi Product Plan ID (PPID).Can you send us confirmation for that.

**Comment by KevinGong2013** [comment]
[https://mfi.apple.com](https://mfi.apple.com)
