### ISSUE TITLE
No text is printing

### ISSUE THREAD

**Issue by umairgillani94** [KevinGong2013/Printer#43]
Running the sample application but it is just printing images and QR and the last line in the blocks. it skips all other lines but adds spaces instead of the text

**Comment by insideApple** [comment]
Hi i have same issue facing did you get any solution?

**Comment by insideApple** [comment]
Hi i found a very strange solution when we add "\n" end of the string it print well

**Comment by KevinGong2013** [comment]
```
let receipt = Receipt(.🖨️58(.ascii))
<<~ .style(.selectsCharacterFont(.c))
<<< "testing"
<<~ .page(.print)
```

Try this code.
