### ISSUE TITLE
How to Print PDF file. 

### ISSUE THREAD

**Issue by ablyJaspreetIOS** [KevinGong2013/Printer#44]
Hello, 
I am Showing a PDF file in a WKWebView. I just wants to know how can i convert the content  to ticket and print that PDF file? Please Help!!

**Comment by ramniwaseasyeat** [comment]
hey this is resolved?

**Comment by ahmedbmostafa** [comment]
any updates ?

**Comment by tanalavijay** [comment]
any update on this?

**Comment by burin-t** [comment]
Convert pdf to image and print image instead.
