### ISSUE TITLE
Set different character code esc/pos command

### ISSUE THREAD

**Issue by JcDenton86** [KevinGong2013/Printer#45]
Hi I would like to pass an ESC/POS command to the printer to set the encoding. 

Specifically trying to pass the 'ESC t n' command where 'n' is a number defined in the character code table.

Based on this pod how can this be done? 

Tried several things with no success.

Thank you in advance

**Comment by KevinGong2013** [comment]
```
let receipt = Receipt(.🖨️58(.ascii))
<<~ .style(.selectsCharacterFont(.c))
```
