### ISSUE TITLE
multiple item

### ISSUE THREAD

**Issue by chitranjank** [KevinGong2013/Printer#47]
how to print multiple item in one by one dynamically?
can I write (var ticket = Ticket()) for  loop?

**Comment by KevinGong2013** [comment]
sure.

**Comment by chitranjank** [comment]
any example?

**Comment by chitranjank** [comment]
> how to print multiple item in one by one dynamically?
> can I write (var ticket = Ticket()) for loop?

**Comment by chitranjank** [comment]
hello Kevin

**Comment by tanalavijay** [comment]
use add block concept for this 
example:
                        self.ticket.add(block: Block(Text(content: tipData, predefined: .bold , .alignment(.left))))
                        self.ticket.add(block: Block(Text(content: totData, predefined: .bold , .alignment(.left))))

**Comment by KevinGong2013** [comment]
```

let receipt = Receipt(.🖨️58(.ascii))
        
receipt.append(item: "dynamically")
receipt.append(item: "content" <<~ .style(.underlineMode(.enable2dot)))
receipt.append(item: Image(cgImage) <<~ .layout(.justification(.center)))

```
