### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by joanmarcs** [KevinGong2013/Printer#5]
Hi! thank you for sharing this. I can't find a way to print a QR code in my receipt. Do you know anything about this?

**Comment by afsalkp123** [comment]
How to print image. Can you help. Thanks in advance.

**Comment by afsalkp007** [comment]
How to print image. Can you help. Thanks in advance.

**Comment by iliakhaburdzania** [comment]
@joanmarcs I think I found solution, now I am waiting Pull request to go through. Before that you can check it out on my Repository

**Comment by fanstudiouk** [comment]
Yes, it would be nice to know how to print an image.

**Comment by janibekm** [comment]
Hi, How to print image? its really good example thank you
