### ISSUE TITLE
Printer is not listing on controller

### ISSUE THREAD

**Issue by smalldevcloud** [KevinGong2013/Printer#54]
<img src="https://user-images.githubusercontent.com/80459916/163674484-6aa764f9-9d62-411f-8d71-17f4158a76d7.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/80459916/163674486-6227a3cb-0d1d-42c5-9593-2facf64148ec.png" width=50% height=50%>

After adding the framework, I do not see a single device in the list of devices. Here's the reason - https://stackoverflow.com/questions/47056562/how-to-connect-thermal-bluetooth-printer-to-ios-devices/51122125#51122125

I found another framework on github. He, as seen in the screenshot, is able to find such 4.0 devices.
https://github.com/RickRedSix/BLE4.0-iOS-Swift-Demo

How to combine these two frameworks to get support for 4.0 BT printers?

**Comment by smalldevcloud** [comment]
https://file.cdn.sunmi.com/SUNMIDOCS/CloudPrinter_IOSSDK_Demo.rar
Also, found this demo for iOS. this is from the manufacturer's website, it finds the printer and communicates with it via bluetooth, apparently, but there is no print example

**Comment by KevinGong2013** [comment]
*How to combine these two frameworks to get support for 4.0 BT printers?*

Just use `Printer` to assemble receipt data.

Write data by another one.
