### ISSUE TITLE
Cannot find operator '<<~' in scope

### ISSUE THREAD

**Issue by kruyvanna** [KevinGong2013/Printer#75]
When running Example I got these erros

<img width="1312" alt="Screenshot 2023-08-02 at 4 58 45 PM" src="https://github.com/KevinGong2013/Printer/assets/1171793/5fe3d61b-d0d9-4a38-b902-6365ef4ecfa5">

**Comment by Muhammadbarznji** [comment]
@kruyvanna  are you import Printer ?

**Comment by kruyvanna** [comment]
I got it to work now. Thank you
