### ISSUE TITLE
Is there any library to use Thermal Printer to Print Over WIFI ??

### ISSUE THREAD

**Issue by jvashisht** [KevinGong2013/Printer#8]
Thank you so much for this library, it helped me alot :)
But i also need to connect printer over wifi and print , Please help me in this if you have idea about this.
Thanks.

**Comment by KevinGong2013** [comment]
Most bluetooth printer is kind of Thermal Printer.
Most modern printers support ESC/POS command set.
Send `Receipt Data`(ESC/POS command Data) over wifi, bluetooth or other transport layer very similar.

**Comment by ramniwaseasyeat** [comment]
Yes, I have changed same code for wifi print, let me know if any one required this

**Comment by xuehaoze** [comment]
> Yes, I have changed same code for wifi print, let me know if any one required this

Hello, would you kindly share some thought regarding to wifi printing? I've tried to connect with my wifi thermal printer for weeks, but never succeed. It would be great if you can give me some hints, thanks!

**Comment by ramniwaseasyeat** [comment]
Sure i will share this one, it’s working in my ios and android devices. You
just need to replace code.

**Comment by ncuthbert** [comment]
Hi @ramniwaseasyeat are you able to share your code for network printing? It would be a big help. I'd be happy to clean up any code to be included in this project. Thanks :)

**Comment by ramniwaseasyeat** [comment]
1. Make TCP Client socket using any socket library and
2. Pass the printer IP address along with the port
3. Make sure your printer connect with the same wifi with your device
4. Convert Tickets data into UTF-8 encoded data

Exm -: 

let client = TCPClient(address: ipAddress, port: Int32(portNumber) ?? 9100)
          switch client.connect(timeout: 3) {
          case .success:
            self.printTicketDesignText(printData!, client, message,true)
            
          case .failure( _):
 ////
          }

**Comment by areeb111** [comment]
@ramniwaseasyeat 
Please can you share the repo fork or send a PR to this repo to support WiFi/Ethernet printers.

**Comment by SHEBINKUNIYIL** [comment]
> Yes, I have changed same code for wifi print, let me know if any one required this

Could you please code developer.shebin@gmail.com
